spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

private:
  key:
    filename: ${PRIVATE_KEY_FILENAME:private_key.der}
public:
  key:
    filename: ${PUBLIC_KEY_FILENAME:public_key.der}
